#!/usr/bin/python3
#
# Assembler for LGP-21 programs.
#
# Usage: lgp21-assembler output.txt input.asm

import argparse
import sys
import lgp21.assem as assem
import lgp21.charset as charset
import lgp21.codegen as codegen
import lgp21.hexadecimal as hexadecimal
import lgp21.insn as insn

# Parse the command-line arguments.
parser = argparse.ArgumentParser(
    prog='lgp21-assembler',
    description='Assembler for the LGP-21 machine'
)
parser.add_argument(
    'output_filename',
    help='name of the output file from the assembler'
)
parser.add_argument(
    'input_filename',
    help='name of the input assembly source file'
)
parser.add_argument(
    '-b', '--binary',
    action='store_true',
    help='output a 6-bit binary tape image instead of ASCII'
)
parser.add_argument(
    '-r', '--relocatable',
    action='store_true',
    help='output a relocatable image with no starting origin'
)
parser.add_argument(
    '-w', '--words-per-line',
    type=int,
    default=8,
    help='set the number of words per line on the output tape'
)
args = parser.parse_args()

# Create a code generator for the output.
code = codegen.CodeGenerator()
code.relocatable = args.relocatable

# Process the input source file.  Stop if there are any errors.
assem.assemble_input(code, args.input_filename)
if code.errors or not code.resolve():
    sys.exit(1)

# Generate the output tape image.
tape_ascii = code.to_tape(max_words_per_line=args.words_per_line)
try:
    if args.binary:
        tape_6bit = charset.io_ascii_to_6bit(tape_ascii, as_list=True)
        tape_punch = charset.io_6bit_to_punch(tape_6bit)
        with open(args.output_filename, 'wb') as file:
            file.write(bytes(tape_punch))
    else:
        with open(args.output_filename, 'w') as file:
            file.write(tape_ascii)
except OSError:
    code.error(args.output_filename, 'could not write to output file')
    sys.exit(1)
sys.exit(0)

# Test code for the CodeGenerator class that prints "he11orld" only.
# This will be replaced with a proper assembler later.

location = 'filename.asm:1'
cg.PC = codegen.dec_to_hex_address(1000)

start = cg.label_for_PC('start', location)
cg.set_entry_point(start)

msg = cg.get_label('msg', location)
i = codegen.Instruction(location)
i.set_order(insn.BRING)
i.set_label(msg)
cg.add_instruction(i)

for n in range(0, 5):
    i = codegen.Instruction(location)
    i.set_order(insn.PRINT6)
    i.set_address(codegen.dec_to_hex_address(200))
    cg.add_instruction(i)
    i = codegen.Instruction(location)
    if i != 4:
        i.set_order(insn.INPUT6)
        i.set_address(codegen.dec_to_hex_address(6200))
        cg.add_instruction(i)

i.set_order(insn.BRING)
i.set_label(msg)
i.set_offset(1) # msg+1
cg.add_instruction(i)

for n in range(0, 3):
    i = codegen.Instruction(location)
    i.set_order(insn.PRINT6)
    i.set_address(codegen.dec_to_hex_address(200))
    cg.add_instruction(i)
    i = codegen.Instruction(location)
    if i != 2:
        i.set_order(insn.INPUT6)
        i.set_address(codegen.dec_to_hex_address(6200))
        cg.add_instruction(i)

i = codegen.Instruction(location)
i.set_order(insn.STOP)
cg.add_instruction(i)

cg.label_for_PC('msg', location)
i = codegen.Instruction(location)
i.set_literal(0xC651868C)
cg.add_instruction(i)
i = codegen.Instruction(location)
i.set_literal(0x34655000)
cg.add_instruction(i)

cg.resolve()
print(cg.to_tape(), end='')
