#!/usr/bin/python3
#
# Run the machine emulator and bootstrap into the "Program Input Routine".
#
# Usage: lgp21-run [options]

import argparse
import sys
import lgp21.assem as assem
import lgp21.charset as charset
import lgp21.codegen as codegen
import lgp21.machine as machine

# Parse the command-line arguments.
parser = argparse.ArgumentParser(
    prog='lgp21-run',
    description='Run programs for the LGP-21 machine'
)
parser.add_argument(
    '-t', '--tape',
    help='name of a tape to load after PIR'
)
parser.add_argument(
    '-u', '--reader-tape',
    help='name of a tape to load on the main tape reader'
)
parser.add_argument(
    '-b', '--binary',
    action='store_true',
    help='tape image is binary instead of ASCII'
)
parser.add_argument(
    '-a', '--assembly-source',
    help='name of a source file to assemble and load'
)
parser.add_argument(
    '-v', '--verbose',
    action='store_true',
    help='print instructions as they are executed'
)
parser.add_argument(
    '-s', '--stop-on-halt',
    action='store_true',
    help='halt stops the emulator'
)
parser.add_argument(
    '-r', '--randomize-memory',
    action='store_true',
    help='randomize the initial memory contents'
)
parser.add_argument(
    '-T', '--time',
    action='store_true',
    help='print the estimated runtime on exit'
)
parser.add_argument(
    '-B', '--bootstrap',
    action='store_true',
    help='bootstrap from the tape, do not load PIR'
)
args = parser.parse_args()
if args.bootstrap:
    # Direct bootstrap always stops on halt.
    args.stop_on_halt = True

with machine.Machine() as mach:
    if args.verbose:
        mach.verbose = True
    if args.randomize_memory:
        mach.randomize_memory()
    if not args.bootstrap:
        # No custom bootstrap, so do the standard bootstrap.
        mach.bootstrap()
    if args.tape:
        if args.bootstrap:
            mach.bootstrap_from_tape(args.tape, binary=args.binary)
        else:
            mach.load_tape(args.tape, binary=args.binary)
    if args.reader_tape:
        mach.load_reader_tape(args.reader_tape, binary=args.binary)
    if args.assembly_source:
        # Assemble and load the supplied source file.
        code = codegen.CodeGenerator()
        assem.assemble_input(code, args.assembly_source)
        if code.errors or not code.resolve():
            sys.exit(1)
        if args.bootstrap:
            # Bootstrap the assembled binary straight in.
            tape_data = code.to_bootstrap_tape()
            mach.bootstrap_from_tape('', raw_data=tape_data)
        else:
            tape_data = code.to_tape()
            mach.pre_typed_input += charset.io_ascii_to_6bit(tape_data, as_list=True)
    mach.BS = 32 # Auto-run when a "." command is seen.
    try:
        while True:
            # Run the machine until it halts.
            mach.run()
            if args.stop_on_halt:
                break

            # Reset and jump back into the "Program Input Routine".
            mach.A = 0
            mach.C = 0
            mach.overflow = False
            mach.resume()
    except KeyboardInterrupt:
        if args.time:
            mach.print_time()
        sys.exit(0)
    if args.time:
        mach.print_time()
